@startuml Animal Sanctuary

class Species {
  +species_id
  +species_name
  -price
  +__construct()
  +get_species_name()
  +get_species_price()
}

class Breeds extends Species{
  +breeds_id
  +breed_name
  +is_mixed
  -price
  +__construct()
  +get_breed_name()
  +get_is_mixed()
  +get_breed_price()
}

class Pets extends Breeds{
  +pets_id
  +pets_age
  +pets_gender
  +pets_neutered
  -price
  +__construct()
  +get_pets_age()
  +get_pets_gender()
  +get_pets_neutered()  
}

class Toys {
  +toys_id
  +toy_name
  -price
  +__construct()
  +get_toy_name()
  +get_toy_price()
}

@enduml